top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/modules/debug
builddir     = /home/dinglin/文档/httpd-2.2.17/modules/debug
VPATH        = /home/dinglin/文档/httpd-2.2.17/modules/debug
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
