top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/modules
builddir     = /home/dinglin/文档/httpd-2.2.17/modules
VPATH        = /home/dinglin/文档/httpd-2.2.17/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

