top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/os
builddir     = /home/dinglin/文档/httpd-2.2.17/os
VPATH        = /home/dinglin/文档/httpd-2.2.17/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
