top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/server/mpm/prefork
builddir     = /home/dinglin/文档/httpd-2.2.17/server/mpm/prefork
VPATH        = /home/dinglin/文档/httpd-2.2.17/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
