#!/bin/bash 

#export a='asdf';

path_install_php="/usr/local/php-5.3.x"
path_install_apache="/usr/local/httpd-2.2.x"

# if install php
is_php_ins=`php -version`
if [ "$?" = 0 ]
then
    echo "php has installed"
    exit
fi

# install GCC
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install autoconf

# get php ext
sudo apt-get install libxml2
sudo apt-get install libxml2-dev
sudo apt-get install libevent-1.4-2
sudo apt-get install libevent-dev
sudo apt-get install bzip2
sudo apt-get install libbz2-dev
sudo apt-get install libcurl3-gnutls
sudo apt-get install libcurl4-gnutls-dev
sudo apt-get install libpng12-0
sudo apt-get install libpng12-dev
sudo apt-get install libjpeg8
sudo apt-get install libjpeg8-dev
sudo apt-get install libfreetype6
sudo apt-get install libfreetype6-dev
sudo apt-get install libmcrypt4
sudo apt-get install libmcrypt-dev
sudo apt-get install libtidy-0.99-0
sudo apt-get install libtidy-dev

ln -s /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/
ln -s /usr/lib/x86_64-linux-gnu/libpng.a /usr/lib/
ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/

#configure
cd 
./configure \
--prefix="$path_install_php" \
--with-mysql=mysqlnd \
--with-gd \
--with-jpeg-dir \
--with-png-dir \
--with-zlib \
--with-freetype-dir \
--enable-gd-native-ttf \
--enable-mbstring \
--enable-sockets \
--with-curl \
--with-pdo-mysql=mysqlnd \
--with-apxs2="$path_install_apache"/bin/apxs 

make
make install

#service=memcached

#extension=memcache.so
wget http://pecl.php.net/get/memcache-2.2.5.tgz
tar -xvf memcache-2.2.5.tgz
cd memcache-2.2.5
"$path_install_php"/bin/phpize
./configure --with-php-config="$path_install_php"/bin/php-config
make
make install

#extension=xcache.so
wget http://xcache.lighttpd.net/pub/Releases/1.3.0/xcache-1.3.0.tar.bz2
tar -xjvf xcache-1.3.0.tar.bz2
cd xcache-1.3.0
"$path_install_php"/bin/phpize
./configure --with-php-config="$path_install_php"/bin/php-config
make
make install

#service=solr
#extension=solr.so
wget http://pecl.php.net/get/solr-0.9.11.tgz
tar -xvf solr-0.9.11.tgz
cd solr-0.9.11
"$path_install_php"/bin/phpize
./configure --with-php-config="$path_install_php"/bin/php-config
make
make install

#service redis
#extension=redis.so

extension=msgpack.so
extension=zmq.so
extension=ldap.so
extension=bcmath.so
extension=soap.so
extension=vld.so
extension=openssl.so
extension=imagick.so
#extension=mongo.so

[Xdebug]                                                                         
zend_extension ="/usr/local/php-5.3.x/lib/php/extensions/no-debug-non-zts-20090626/xdebug.so"
xdebug.profiler_enable=on                                                        
xdebug.trace_output_dir="/usr/local/php-5.3.x/xdebug/"                           
xdebug.profiler_output_dir="/usr/local/php-5.3.x/xdebug/"                        
xdebug.remote_enable=on                                                          
xdebug.remote_handler=dbgp                                                       
;xdebug.remote_host=localhost                                                    
xdebug.remote_port=9999                                                          
[xhprof]                                                                         
extension=xhprof.so                                                              
xhprof.output_dir=/tmp/xhprof  




