top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/server/mpm
builddir     = /home/dinglin/文档/httpd-2.2.17/server/mpm
VPATH        = /home/dinglin/文档/httpd-2.2.17/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
