top_srcdir   = /home/dinglin/文档/httpd-2.2.17
top_builddir = /home/dinglin/文档/httpd-2.2.17
srcdir       = /home/dinglin/文档/httpd-2.2.17/modules/mappers
builddir     = /home/dinglin/文档/httpd-2.2.17/modules/mappers
VPATH        = /home/dinglin/文档/httpd-2.2.17/modules/mappers

include $(top_srcdir)/build/special.mk

